env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - plugin:prettier/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
settings:
  react:
    version: detect
plugins:
  - react
  - "@typescript-eslint"
rules:
  "@typescript-eslint/explicit-module-boundary-types": off
  no-empty-pattern:
    - warn
  "@typescript-eslint/no-empty-interface":
    - warn
    - allowSingleExtends: true
  no-console:
    - warn
  end-ofLine: off
